# fly.toml app configuration file generated for williamk19-com on 2024-11-30T08:52:20+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'williamk19-com'
primary_region = 'sin'

[build]

[env]
  NEXT_PUBLIC_PB_URL = 'https://pb.williamk19.com'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
